# Generated by Django 4.1.8 on 2023-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_type_userconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_code_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserConfirmation',
        ),
    ]
