# Generated by Django 4.2 on 2023-04-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_attributes',
            field=models.JSONField(blank=True),
        ),
    ]
